### ISSUE TITLE
Generate cover page

### ISSUE THREAD

**Issue by henrik-berglund** [ProAgileAB/agile-team-development#16]
If we generate full pdf with command pandoc Team-Start-Example.md Repairing-Broken-Agreements.md -o test.pdf -H style\footer.tex --toc --toc-depth=1 --top-level-division=chapter 

We need a way to add a cover page that will not end up after TOC/in TOC. 

Parhaps this should be done by just pandoc -Dlatex > latex_template
and then editing the template to include a TOC. Or maybe the standard template contains variables that we can set as YAML in the MD file to avoid using a custom template

**Comment by e1th0r** [comment]
working in this requiremente

**Comment by henrik-berglund** [comment]
This is not far from completion. The file test.sh generates a decent cover page. What remains is just to simplify/cutomize tyhe custom template a bit and include the ProAgile logo

**Comment by henrik-berglund** [comment]
Fixed this by some very simple editing of a web example

**Comment by e1th0r** [comment]
Hi.

Have you read my last commit?

My last commit is a proposal for cover page using a custom template. 

Please take a look; I upload all my proposal in one different folder called "proposal" ; in this folder you will  find individual pdfs and full pdf.

Regards
