### ISSUE TITLE
Wrong header level role study Sam/Chris. Mve to level 2 and regenerate pdfs

### ISSUE THREAD

**Issue by henrik-berglund** [ProAgileAB/agile-team-development#17]

**Comment by e1th0r** [comment]
working in this requiremente

**Comment by e1th0r** [comment]
Working in this requirement

**Comment by henrik-berglund** [comment]
Three ideas on how to fix this:
- Somehow insert \cleardoublepage in .md files from genpdfs script. Unclear if this is possible
- Somehow insert \cleardoublepage in intermediate latex files from genpdfs script. Unclear if this is possible. First attempts of splitting build into md -> latex , latex -> pdf did not retain format of .md -> latex flow
- Format these chapters as heading I and remove them from TOC somehow

**Comment by henrik-berglund** [comment]
Removed /pagebreak from md file. This deos not render HTML properly. Pdf generation looks fine though now...
