### ISSUE TITLE
Cover in proposal folder

### ISSUE THREAD

**Issue by henrik-berglund** [ProAgileAB/agile-team-development#21]
Can you remove the ProAgileAB from the front page? We already have the logo, so that should be enough

The text "For updates to this guide, please visit proagile.se/teams is also missing from front page

**Comment by henrik-berglund** [comment]
Veriosn numenr and date missing also. See generated cover in folder above

**Comment by e1th0r** [comment]
This requirement added complex work because we need to rewrite complete template sections..

So, we will be removing proposal folder and we will focus on fix issues on old files

**Comment by e1th0r** [comment]
Not proceed because we aren't work on proposal folder just on old files
