### ISSUE TITLE
Titles are too far down the page in pdfs in the proposal folder

### ISSUE THREAD

**Issue by henrik-berglund** [ProAgileAB/agile-team-development#23]
Each chapter is a simple paper. I do not think having the title so far down the page matches this.

Can you please make the title start at the same position as the text on normal pages.

**Comment by e1th0r** [comment]
This requirement added complex work because we need to rewrite complete template sections..

So, we will be removing proposal folder and we will focus on fix issues on old files

**Comment by e1th0r** [comment]
Not proceed because we aren working on proposal just in old files
